### PR TITLE
Shade build

### PR DESCRIPTION
**Pull request by scrudden**
HI Mike,

This is a change to the pom for shade and a change to schema generator. It seems the whole file for SchemaGenerator appears changed but it has not. The getClasses method is what I changed.

Cheers,

Sean.

### CODE REVIEW

**Comment by skibu** [comment]
Looks good. For some reason the diff shows that every line in SchemaGenerator changed, so it is much more difficult to see what the changes really are. I'm taking a wild guess that the line terminators changed for that file.

**Comment by scrudden** [comment]
Hi Mike,

Yep must be cr/lf. Will watch for this the next time. I have been switching between windows and linux.

Cheers,

Sean.

**Comment by barbeau** [comment]
FYI, for future use - I ran into this whitespace issue a few months ago - there are a ton (too many) different ways to deal with fixing this in Git if you've already done the commit, but not yet submitted the PR.  I've found the easiest way to fix it is to create a new branch, and then do:

`git rebase --whitespace=fix HEAD^`

This will re-commit the same code that was in the last commit, but without including the whitespace changes.  If there are X commits, you can do:

`git rebase --whitespace=fix HEAD~X`

Then, you can submit the PR from this branch and it won't have the whitespace issues.

Of course, the best way is to not include the cr/lf changes to begin with, but if you did, I found the above git command is the easiest way to fix it.

See also http://stackoverflow.com/a/19156679/937715.

**Comment by scrudden** [comment]
Thanks Sean, I'm a GIT novice so all pointers are welcome.

**Comment by barbeau** [comment]
Yeah, I had to go up against the Git learning curve myself over the last few years - it's hugely powerful, but also has a huge learning curve.  It's especially confusing if you're coming from another version control system like SVN.  Figured I'd save you an hour or so of Googling, which is what it took me to come up with the above one line :).

**Pull request merged**
